[package]
name = "acfunliveapi"
version = "0.1.0"
authors = ["orzogc <orzogc@163.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.50"
cookie = "0.15.0"
pretend = "0.2.0"
pretend-reqwest = "0.2.0"
reqwest = { version = "0.11.3", default-features = false, features = ["rustls-tls", "gzip"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
thiserror = "1.0.25"

[dev-dependencies]
tokio = { version = "1.7.0", features = ["rt-multi-thread", "macros"] }
